# Form implementation generated from reading ui file '/home/astorec/Documents/Repos/BeybladeTournamentManger/BTMPY/src/GUI/bracket_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(328, 120)
        self.p1_label = QtWidgets.QLabel(parent=Form)
        self.p1_label.setGeometry(QtCore.QRect(20, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p1_label.setFont(font)
        self.p1_label.setObjectName("p1_label")
        self.p2_label = QtWidgets.QLabel(parent=Form)
        self.p2_label.setGeometry(QtCore.QRect(20, 50, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p2_label.setFont(font)
        self.p2_label.setObjectName("p2_label")
        self.bracket_frame = QtWidgets.QFrame(parent=Form)
        self.bracket_frame.setGeometry(QtCore.QRect(0, 0, 321, 111))
        self.bracket_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.bracket_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bracket_frame.setObjectName("bracket_frame")
        self.edit_btn = QtWidgets.QPushButton(parent=self.bracket_frame)
        self.edit_btn.setGeometry(QtCore.QRect(120, 80, 81, 24))
        self.edit_btn.setObjectName("edit_btn")
        self.complete_btn = QtWidgets.QPushButton(parent=self.bracket_frame)
        self.complete_btn.setGeometry(QtCore.QRect(120, 80, 81, 24))
        self.complete_btn.setObjectName("complete_btn")
        self.p2_score = QtWidgets.QSpinBox(parent=self.bracket_frame)
        self.p2_score.setGeometry(QtCore.QRect(280, 50, 31, 21))
        self.p2_score.setObjectName("p2_score")
        self.p1_score = QtWidgets.QSpinBox(parent=self.bracket_frame)
        self.p1_score.setGeometry(QtCore.QRect(280, 10, 31, 21))
        self.p1_score.setObjectName("p1_score")
        self.bracket_frame.raise_()
        self.p1_label.raise_()
        self.p2_label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.p1_label.setText(_translate("Form", "Player 1"))
        self.p2_label.setText(_translate("Form", "Player 2"))
        self.edit_btn.setText(_translate("Form", "Edit"))
        self.complete_btn.setText(_translate("Form", "Complete"))
