# Form implementation generated from reading ui file '/home/astorec/Documents/Repos/BeybladeTournamentManger/BTMPY/src/GUI/import_tournament.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 114)
        self.import_btns = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.import_btns.setGeometry(QtCore.QRect(30, 70, 341, 32))
        self.import_btns.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.import_btns.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.import_btns.setCenterButtons(True)
        self.import_btns.setObjectName("import_btns")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label.setObjectName("label")
        self.tournament_url_text = QtWidgets.QTextEdit(parent=Dialog)
        self.tournament_url_text.setGeometry(QtCore.QRect(130, 30, 241, 31))
        self.tournament_url_text.setObjectName("tournament_url_text")

        self.retranslateUi(Dialog)
        self.import_btns.accepted.connect(Dialog.accept) # type: ignore
        self.import_btns.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Tournent URL"))
